version: '3.8'

services:
  api:
    build: .
    container_name: file_guard_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - file_guard_network

  mongo:
    image: mongo:latest
    container_name: file_guard_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - file_guard_network

volumes:
  mongo_data:

networks:
  file_guard_network:
    driver: bridge
