#!/usr/bin/env bash
# Deploy FileIntegrity contract to Anvil and save deployment info

set -e

echo "Starting Anvil deployment..."

# Check if Anvil is running
if ! curl -s http://127.0.0.1:8545 > /dev/null 2>&1; then
    echo "ERROR: Anvil is not running on http://127.0.0.1:8545"
    echo "Start Anvil with: anvil"
    exit 1
fi

# Set PATH for forge
export PATH="$HOME/.foundry/bin:$PATH"

# Load private key from environment or use provided value
if [ -z "$DEPLOY_PRIVATE_KEY" ]; then
    echo "ERROR: DEPLOY_PRIVATE_KEY environment variable not set"
    echo ""
    echo "Usage:"
    echo "  export DEPLOY_PRIVATE_KEY=0xYourPrivateKeyHere"
    echo "  ./scripts/deploy_contract.sh"
    echo ""
    echo "For local Anvil testing, get a private key from Anvil's startup output"
    exit 1
fi

PRIVATE_KEY="$DEPLOY_PRIVATE_KEY"

echo "Compiling contract..."
forge build

echo "Deploying FileIntegrity contract to Anvil..."
DEPLOY_OUTPUT=$(forge create contracts/FileIntegrity.sol:FileIntegrity \
    --rpc-url http://127.0.0.1:8545 \
    --private-key $PRIVATE_KEY \
    2>&1)

echo "$DEPLOY_OUTPUT"

# Extract contract address
CONTRACT_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep "Deployed to:" | awk '{print $3}')

if [ -z "$CONTRACT_ADDRESS" ]; then
    echo "ERROR: Failed to extract contract address"
    exit 1
fi

echo ""
echo "Contract deployed successfully!"
echo "Contract Address: $CONTRACT_ADDRESS"
echo ""

# Get Web3 provider from environment or use default
WEB3_PROVIDER="${WEB3_PROVIDER_URI:-http://127.0.0.1:8545}"

# Save deployment info (without exposing private key)
cat > backend/.env.blockchain << EOF
# Blockchain Configuration - Generated by scripts/deploy_contract.sh
# WARNING: Add this file to .gitignore - it contains sensitive data
WEB3_PROVIDER_URI=$WEB3_PROVIDER
ETH_PRIVATE_KEY=$PRIVATE_KEY
CONTRACT_ADDRESS=$CONTRACT_ADDRESS
EOF

echo "Deployment config saved to backend/.env.blockchain"
echo ""
echo "Next steps:"
echo "  1. Source the blockchain config:"
echo "     source backend/.env.blockchain"
echo ""
echo "  2. Or manually add to your backend/.env file:"
echo "     WEB3_PROVIDER_URI=$WEB3_PROVIDER"
echo "     ETH_PRIVATE_KEY=<your_private_key>"
echo "     CONTRACT_ADDRESS=$CONTRACT_ADDRESS"
echo ""
echo "  3. Make sure backend/.env.blockchain is in .gitignore"
echo ""
echo "Ready to anchor file hashes on-chain!"
